### ISSUE TITLE
testCgalEigenQuadraticProgramming fails

### ISSUE THREAD

**Issue by BrettHemes-3M** [gaschler/bounding-mesh#12]
per the title, the testCgalEigenQuadraticProgramming gives the following output:

> ./testCgalEigenQuadraticProgramming 
qem:   0.1     0 -0.02   0.3
    0     1     0     0
-0.02     0     1     0
  0.3     0     0  0.47
Number of constraints: 0
Solving 10 repetitions.
terminate called after throwing an instance of 'CGAL::Assertion_exception'
  what():  CGAL ERROR: assertion violation!
Expr: j <= i
File: /usr/include/CGAL/QP_models.h
Line: 809
Aborted (core dumped)

I am on Ubuntu 16.04 and have cgal 4.7-4 installed

**Comment by gaschler** [comment]
Note that the default compile setting of boundingmesh is to use QuadProg++ QP::solve_quadprog, not the CGAL::solve_quadratic_program method where this test case aborts.
I usually don't test the CGAL alternative much. If the main library also catches a CGAL_ERROR, I would like to have that fixed.

**Comment by gaschler** [comment]
This unfinished optimizer test was removed.
