### ISSUE TITLE
bounding-mesh does not provide any way to install the core boundingmesh library

### ISSUE THREAD

**Issue by kyoDralliam** [gaschler/bounding-mesh#2]
I would like to use the bounding-mesh core library as an optional dependency and would like to let the user of my application the choice to install the boundingmesh library.

Is there any reason not to provide an installation script for the core library and only installing the binaries ? If not, I can PR the cmake script that I am currently using to install it.

**Comment by gaschler** [comment]
Sure, I will accept a pull request for this. It would also be good to set the version in the library (set_property).

**Comment by gaschler** [comment]
Thanks for your patch. I rewrote much of it for a smaller solution and merged. For custom install paths, please use CMAKE_INSTALL_PREFIX
