### ISSUE TITLE
Broken links in README.md

### ISSUE THREAD

**Issue by Levi-Armstrong** [gaschler/bounding-mesh#4]
Hello, I attended your presentation at the RSS Workshop and I am interested in using this for model simplification for ROS. I am also interested in the items below listed in the readme but the links appear to be broken.
- Voxelize
- Approximate Convex Decomposition
- Convex Decomposition

**Comment by gaschler** [comment]
Currently, the bounding convex decomposition feature is being developed in a private branch and needs some cleaning up. (That is why the readme is not in sync.) Thanks for your interest. I promise to publish the bounding convex decomposition software soon.
Until then, I will keep this issue open.

**Comment by gaschler** [comment]
Ok, you can find the bounding convex decomposition software in the repo. A new dependency is now CGAL (for convex hulls). Compile and run `./bounding-convex-decomposition`
